Normalize JAR paths before conditional
In a Docker 12.04 container and a clean 12.04 VM image singlejar fails
with the message:

    Exception: Cannot find jython jar

Because the if condition on L257 and L260 is receiving the path:

    /opt/jython-ssl/dist/bin/jython/../../jython-dev.jar

This normalizes the path before testing it.